### ISSUE TITLE
Backtest

### ISSUE THREAD

**Issue by crazy25000** [PeterMalkin/oandapybot#1]
Hey, how do you implement takeprofit, stoploss, and trailing stop for the backtest in pips? Keep getting errors or not working properly.

**Comment by PeterMalkin** [comment]
To have stoploss and trailing stop be a fixed pip, not a volume based (ATR),

you would just modify
logic/stoploss.py and logic/trailingstop.py

In particular, you want to change GetPrice() function

**Comment by crazy25000** [comment]
Ah I see, thank you! Would you test the backtest again? I ran it with default settings, using the default CSV and received this error in the log:

```
AttributeError: 'Strategy' object has no attribute '_stoploss'
```

The stoploss and take profit are not working, even when importing the stoploss class to fix the above error.

To test this, I changed the ATR to multiply by different numbers, but the result of PnL at the end was always the same. Didn't change anything else, just wanted to make sure they were working.

**Comment by crazy25000** [comment]
I figured it out, just rewrote the strategy class. Question, how would I be able to calculate the MACDSIGNAL? I can calculate the MACD since its fast ema - slow ema, but not sure how to apply EMA to MACD with a period. I'm trying to stick to your coding method. MACDSIGNAL = (MACD, period=9)

**Comment by PeterMalkin** [comment]
You would do something like this:

```
    macd,macdsignal,macdhist = talib.MACD(numpy.array(candles_close_prices), macd_fast_period, macd_slow_period, macd_signal_period)
    macdsignal = macdsignal[-1]
```
